name: Git Version

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0  # Fetch the whole repo history

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '22'  # Correctly set to the latest Node.js version

      - name: Cache Node.js dependencies
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Git Version
        id: version
        uses: codacy/git-version@2.8.0
        
      - name: Use the version
        run: echo ${{ steps.version.outputs.version }}
        
      - name: Use the previous version
        run: echo ${{ steps.version.outputs.previous-version }}
